name: CI devops 2024
on:
  # Lancement sur les branches main et lors des pull requests
  push:
    branches: 
      - main
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      # Checkout du code source
      - uses: actions/checkout@v2.5.0

      # Configuration de JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Build et tests avec Maven dans le répertoire simple-api
      - name: Build and test with Maven
        run: mvn clean verify
        working-directory: simple-api
